#!/bin/bash

javac -g -cp .:/home/pcurtis/storm-0.8.2/storm-0.8.2.jar:\
/usr/share/maven-repo/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:\
/space/storm/storm-0.8.2/lib/slf4j-api-1.5.8.jar:\
/space/storm/storm-0.8.2/lib/slf4j-log4j12-1.5.8.jar \
 `find . -name "*.java"`
